export type FraudDetectionType = {
	id: string;
	data_key: string;
	full_name: string;
	tahun_1: number;
	tahun_2: number;
	tanggal: string;
	beneish_m: float;
};

export type FraudDetectionFull = {
	data_key: string;
	id_user: string;
	revenue_1: number;
	cogs_1: number;
	sgae_1: number;
	depreciation_1: number;
	net_continuous_1: number;
	account_receivables_1: number;
	current_assets_1: number;
	ppe_1: number;
	securities_1: number;
	total_asset_1: number;
	total_ltd_1: number;
	cash_flow_operate_1: number;
	revenue_2: number;
	cogs_2: number;
	sgae_2: number;
	depreciation_2: number;
	net_continuous_2: number;
	account_receivables_2: number;
	current_assets_2: number;
	ppe_2: number;
	securities_2: number;
	total_asset_2: number;
	total_ltd_2: number;
	cash_flow_operate_2: number;
	tahun_1: number;
	tahun_2: number;
	id_institution: string;
	tanggal: string;
	beneish_m: number;
	dsri: number;
	gmi: number;
	aqi: number;
	sgi: number;
	depi: number;
	sgai: number;
	lvgi: number;
	tata: number;
};
