name: Update Staging on Main Push

on:
  push:
    branches:
      - main

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://RevDonz:${{secrets.GITHUB_TOKEN}}@github.com/RevDonz/fe-fraud.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: staging

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/RevDonz/fe-fraud.git

  # replace "master" with your master branch name
  MASTER_BRANCH: main


jobs:
  update_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge main into staging
        run: |
          git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
          cd tmp
          git config user.name "RevDonz"
          git config user.email "aprilio842@gmail.com"
          git config pull.rebase false
          git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
          git push

# on:
#   push:
#     branches:
#       - "main"
# jobs:
#   merge-branch:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: emiliopedrollo/auto-merge@v1.2.0
#         with:
#           github_token: ${{ github.token }}
#           target_branch: 'staging'
#           source_ref: 'main'